-- MySQL Script generated by MySQL Workbench
-- Sun Jan  9 17:46:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema book_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema book_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book_store` DEFAULT CHARACTER SET utf8 ;
USE `book_store` ;

-- -----------------------------------------------------
-- Table `book_store`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`users` (
  `ID` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(20) NULL,
  `first_name` VARCHAR(20) NULL,
  `last_name` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `phonenumber` VARCHAR(20) NULL,
  `shipping_address` VARCHAR(45) NULL,
  `type` VARCHAR(10) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_store`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`books` (
  `ISBN` VARCHAR(20) NOT NULL,
  `title` VARCHAR(45) NULL,
  `publisher` VARCHAR(45) NULL,
  `publication_year` VARCHAR(4) NULL,
  `selling_price` INT NULL,
  `category` VARCHAR(15) NULL,
  `threshold` INT NULL,
  `copies` INT NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
