-- MySQL Script generated by MySQL Workbench
-- Mon Jan 10 07:00:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
DROP SCHEMA book_store;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema book_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema book_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book_store` DEFAULT CHARACTER SET utf8 ;
USE `book_store` ;

-- -----------------------------------------------------
-- Table `book_store`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`users` (
  `ID` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(20) NULL,
  `first_name` VARCHAR(20) NULL,
  `last_name` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `phonenumber` VARCHAR(20) NULL,
  `shipping_address` VARCHAR(45) NULL,
  `type` VARCHAR(10) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_store`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`publishers` (
  `name` VARCHAR(20) NOT NULL,
  `address` VARCHAR(50) NULL,
  `phonenumber` VARCHAR(20) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_store`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`books` (
  `ISBN` VARCHAR(20) NOT NULL,
  `title` VARCHAR(45) NULL,
  `publisher` VARCHAR(45) NULL,
  `publication_year` VARCHAR(4) NULL,
  `selling_price` INT NULL,
  `category` VARCHAR(15) NULL,
  `threshold` INT NULL,
  `copies` INT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_books_publishers1_idx` (`publisher` ASC) VISIBLE,
  CONSTRAINT `fk_books_publishers1`
    FOREIGN KEY (`publisher`)
    REFERENCES `book_store`.`publishers` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_store`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`authors` (
  `ISBN` VARCHAR(20) NOT NULL,
  `author_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN`, `author_name`),
  CONSTRAINT `fk_authors_books`
    FOREIGN KEY (`ISBN`)
    REFERENCES `book_store`.`books` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_store`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`orders` (
  `user_ID` INT NOT NULL,
  `ISBN` VARCHAR(20) NOT NULL,
  `count` INT NULL,
  `price` INT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`user_ID`, `ISBN`),
  INDEX `fk_orders_books1_idx` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_ID`)
    REFERENCES `book_store`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_books1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `book_store`.`books` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_store`.`shopping_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`shopping_cart` (
  `user_ID` INT NOT NULL,
  `ISBN` VARCHAR(20) NOT NULL,
  `count` INT NULL,
  `price` INT NULL,
  PRIMARY KEY (`user_ID`, `ISBN`),
  INDEX `fk_orders_books1_idx` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users10`
    FOREIGN KEY (`user_ID`)
    REFERENCES `book_store`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_books10`
    FOREIGN KEY (`ISBN`)
    REFERENCES `book_store`.`books` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_store`.`CREDIT_CARD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`CREDIT_CARD` (
  `number` VARCHAR(20) NOT NULL,
  `date` VARCHAR(15) NULL,
  PRIMARY KEY (`number`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
